version: '3'
services:
  conditionservice:
    container_name: conditionservice
    privileged: true
    build:
      context: ../Beta/conditionservice
      dockerfile: Dockerfile
    image: conditionservice:1.0
    ports:
      - "8083:8083"
    restart: always
    volumes:
      - "/Volumes/PRO/workspace/log:/home/conditionservice/log"
    depends_on:
      - mysql
      - redis
      - slaverservice
    networks:
      - autometer-network

  dispatchservice:
    container_name: dispatchservice
    privileged: true
    build:
      context: ../Beta/dispatchservice
      dockerfile: Dockerfile
    image: dispatchservice:1.0
    ports:
      - "8082:8082"
    restart: always
    volumes:
      - "/Volumes/PRO/workspace/log:/home/dispatchservice/log"
    depends_on:
      - mysql
      - redis
      - conditionservice
    networks:
      - autometer-network

  slaverservice:
    container_name: slaverservice
    privileged: true
    build:
      context: ../Beta/slaverservice
      dockerfile: Dockerfile
    image: slaverservice:1.0
    ports:
      - "8081:8081"
    restart: always
    volumes:
      - "/Volumes/PRO/workspace/log:/home/slaverservice/log"
    depends_on:
      - mysql
      - redis
    networks:
      - autometer-network

  testcenterservice:
    container_name: testcenterservice
    privileged: true
    build:
      context: ../Beta/testcenterservice
      dockerfile: Dockerfile
    image: testcenterservice:1.0
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - "/Volumes/PRO/workspace/log:/home/testcenterservice/log"
    depends_on:
      - mysql
      - redis
      - dispatchservice
    networks:
      - autometer-network

  testcenterapp:
    container_name: testcenterapp
    privileged: true
    build:
      context: ../Beta/testcenterapp
      dockerfile: Dockerfile
    image: testcenterapp:1.0
    ports:
      - "8084:80"
    restart: always
    depends_on:
      - testcenterservice
    networks:
      - autometer-network

  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - "/Volumes/PRO/workspace/mysql/data:/var/lib/mysql"
      - "/Volumes/PRO/workspace/mysql/config:/etc/mysql/conf.d"
    networks:
      - autometer-network

  redis:
    container_name: redis
    privileged: true
    image: redis:6.2.6
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - "/Volumes/PRO/workspace/redis/data:/data"
      - "/Volumes/PRO/workspace/redis/config:/etc/redis/redis.conf"
    networks:
      - autometer-network

networks:
  autometer-network:
    driver: bridge